---
title: "R Notebook"
output:
  pdf_document: default
  html_document:
    df_print: paged
---
 

```{r}
install.packages("tidyverse")
library(tidyverse)
install.packages("dplyr")
library(dplyr)
install.packages("ggplot2")
library(ggplot2)
install.packages("cowplot")
library(cowplot)
```

#Shot Chart Court
```{r}
circle_points = function(center = c(0, 0), radius = 1, npoints = 360) {
  angles = seq(0, 2 * pi, length.out = npoints)
  return(data_frame(x = center[1] + radius * cos(angles),
                    y = center[2] + radius * sin(angles)))
}
width = 50
height = 94 / 2
key_height = 19
inner_key_width = 12
outer_key_width = 16
backboard_width = 6
backboard_offset = 4
neck_length = 0.5
hoop_radius = 0.75
hoop_center_y = backboard_offset + neck_length + hoop_radius
three_point_radius = 23.75
three_point_side_radius = 22
three_point_side_height = 14
court_themes = list(
  light = list(
    court = 'floralwhite',
    lines = 'black',
    text = '#222222',
    made = '#00bfc4',
    missed = '#f8766d',
    hex_border_size = 1,
    hex_border_color = "#000000"
  ),
  dark = list(
    court = '#000004',
    lines = '#999999',
    text = '#f0f0f0',
    made = '#00bfc4',
    missed = '#f8766d',
    hex_border_size = 0,
    hex_border_color = "#000000"
  ),
  ppt = list(
    court = 'gray15',
    lines = 'white',
    text = '#f0f0f0',
    made = '#00bfc4',
    missed = '#f8766d',
    hex_border_size = 0,
    hex_border_color = "gray15"
),
  white = list(
    court = 'white',
    lines = 'black',
    text = 'black',
    made = '#00bfc4',
    missed = '#f8766d',
    hex_border_size = 0,
    hex_border_color = "gray15"
)
)
plot_court = function(court_theme = court_themes$light, use_short_three = FALSE) {
  if (use_short_three) {
    three_point_radius = 22
    three_point_side_height = 0
  }
  
  court_points = data_frame(
    x = c(width / 2, width / 2, -width / 2, -width / 2, width / 2),
    y = c(height, 0, 0, height, height),
    desc = "perimeter"
  )
  
  court_points = bind_rows(court_points , data_frame(
    x = c(outer_key_width / 2, outer_key_width / 2, -outer_key_width / 2, -outer_key_width / 2),
    y = c(0, key_height, key_height, 0),
    desc = "outer_key"
  ))
  
  court_points = bind_rows(court_points , data_frame(
    x = c(-backboard_width / 2, backboard_width / 2),
    y = c(backboard_offset, backboard_offset),
    desc = "backboard"
  ))
  
  court_points = bind_rows(court_points , data_frame(
    x = c(0, 0), y = c(backboard_offset, backboard_offset + neck_length), desc = "neck"
  ))
  
  foul_circle = circle_points(center = c(0, key_height), radius = inner_key_width / 2)
  
  foul_circle_top = filter(foul_circle, y > key_height) %>%
    mutate(desc = "foul_circle_top")
  
  foul_circle_bottom = filter(foul_circle, y < key_height) %>%
    mutate(
      angle = atan((y - key_height) / x) * 180 / pi,
      angle_group = floor((angle - 5.625) / 11.25),
      desc = paste0("foul_circle_bottom_", angle_group)
    ) %>%
    filter(angle_group %% 2 == 0) %>%
    select(x, y, desc)
  
  hoop = circle_points(center = c(0, hoop_center_y), radius = hoop_radius) %>%
    mutate(desc = "hoop")
  
  restricted = circle_points(center = c(0, hoop_center_y), radius = 4) %>%
    filter(y >= hoop_center_y) %>%
    mutate(desc = "restricted")
  
  three_point_circle = circle_points(center = c(0, hoop_center_y), radius = three_point_radius) %>%
    filter(y >= three_point_side_height, y >= hoop_center_y)
  
  three_point_line = data_frame(
    x = c(three_point_side_radius, three_point_side_radius, three_point_circle$x, -three_point_side_radius, -three_point_side_radius),
    y = c(0, three_point_side_height, three_point_circle$y, three_point_side_height, 0),
    desc = "three_point_line"
  )
  
  court_points = bind_rows(
    court_points,
    foul_circle_top,
    foul_circle_bottom,
    hoop,
    restricted,
    three_point_line
  )
  
  
  court_points <- court_points
  
  ggplot() +
    geom_path(
      data = court_points,
      aes(x = x, y = y, group = desc),
      color = court_theme$lines, sizes = 2
    ) +
    coord_fixed(ylim = c(0, 45), xlim = c(-25, 25)) +
    theme_minimal(base_size = 22) +
    theme(
      text = element_text(color = court_theme$text),
      plot.background = element_rect(fill = 'gray15', color = 'gray15'),
      panel.background = element_rect(fill = court_theme$court, color = court_theme$court),
      panel.grid = element_blank(),
      panel.border = element_blank(),
      axis.text = element_blank(),
      axis.title = element_blank(),
      axis.ticks = element_blank(),
      legend.background = element_rect(fill = court_theme$court, color = court_theme$court),
      legend.margin = margin(-1, 0, 0, 0, unit = "lines"),
      legend.position = "bottom",
      legend.key = element_blank(),
      legend.text = element_text(size = rel(1.0))
    )
}
```

```{r}
shots_data <- read_csv("NBA_2004_2023_Shots.csv")
shots_data
```
#Dataset
```{r}

shots <- shots_data %>% filter(TEAM_NAME == "Miami Heat" ) %>%
    filter(SEASON_2 == "2011-12") %>% filter(EVENT_TYPE == "Made Shot" ) %>% filter(PLAYER_NAME == "LeBron James")
shots
```
#Shot Chart
```{r}
plot_court(court_themes$white, use_short_three = F) +
#plot shot "points" with x & y locations
  geom_point(data = shots, aes(x = LOC_X, y = LOC_Y, color = SHOT_MADE, fill = SHOT_MADE), 
             size =3, shape = 21, stroke = .5) +
  # ---- plot team logo (remove these 2 lines if you're plotting multiple teams!)
  draw_image(paste0("https://cdn.nba.com/logos/nba/", unique(shots$TEAM_ID), "/primary/L/logo.svg"), 
             x = -28, y = 34, width = 12, height = 12) +
  # ---- fill the points with color
  scale_color_manual(values = c("green4","red3"), aesthetics = "color", breaks = c("TRUE", "FALSE"), labels=c("Made", "Missed")) +
  scale_fill_manual(values = c("green2","red2"), aesthetics = "fill", breaks = c("TRUE", "FALSE"), labels=c("Made", "Missed")) +
  # ----
  scale_x_continuous(limits = c(-27.5, 27.5)) +
  scale_y_continuous(limits = c(0, 45)) +
  # ---- Add title and subtitle (manual!)
  labs(
    title = "Lebron James 2011-2012 Shot Chart",
    subtitle = ""
  ) +
  # ----
  annotate(geom = 'text', x = 0, y = 2, hjust = .5, 
        label = "", size = 2, color = "black", face = "bold") +
  # ---- Theme options for manipulating the look of the plot
  theme(
        legend.direction = "horizontal",
        legend.title = element_blank(),
        legend.text = element_text(hjust = .5, size = 7, face = "bold", colour = "black"),
        legend.background = element_rect(fill = "white", colour = "white"),
        legend.box.background = element_rect(fill = "white", colour = "white"),
        legend.key = element_rect(fill = "white", colour = "white"),
        legend.margin = margin(t = -.5, unit='cm'),
        legend.box.margin=margin(-15,0,15,0),
        #
        plot.background = element_rect(fill="white", color = "white"),
        panel.background = element_rect(fill="white", color = "white"),
        #
        plot.title = element_text(hjust = 0.5, size = 22, vjust = -9, face = "bold", colour = "black"),
        plot.subtitle = element_text(hjust = 0.5, size = 12, vjust = -15, face = "bold", colour = "black"), 
        plot.margin = margin(0, 0, .5, 0, "cm"),
        )
```

```{r}
# Packages
install.packages("tidyverse")
library(tidyverse)
install.packages("rvest")
library(rvest)
install.packages("dplyr")
library(dplyr)
install.packages("janitor")
library(janitor)
install.packages("prismatic")
library(prismatic)

```
```{r}
install.packages("ggrepel")
library(ggrepel)
install.packages("geomtextpath")
library(geomtextpath)
```


```{r}
ratings = read_csv("ratings.csv")
ratings
```


# Scatter plot
```{r}
nba <- ratings %>%
ggplot(aes(x = Offense, y = defense, label = Player)) +
geom_smooth(method = "lm", color = "gray25", fill = "gray20") +
geom_point(aes(fill = "red", color = after_scale(clr_darken(fill, 0.3))), 
             shape = 21, 
             alpha = .75, 
             size = 3) +
  geom_vline(xintercept = 120,color="white") +
  annotate(geom="text", x=122, y=94, label="Great Offense/Great Defense 
           (Where you want to be)",
              color="green",size=3) +  annotate(geom="text", x=117, y=94, label="Good Offense/Great Defense 
           ",
              color="yellow",size=3) +
              annotate(geom="text", x=117, y=110, label="Good Offense/Bad Defense 
          ",
              color="red",size=3)+annotate(geom="text", x=122, y=110, label="Great Offense/Bad Defense 
          ",
              color="yellow",size=3)+
  geom_hline(yintercept = 103,color="white") +
  geom_text_repel(size = 2, color = "white", min.segment.length = unit(0.1, "lines")) +
  theme(
    legend.position = "none",
    plot.background = element_rect(fill = "gray15", colour = "gray15"),
    panel.background = element_rect(fill = "gray15", colour = "gray15"),
    panel.grid.major = element_line(colour = "gray20"),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "lightgrey"),
    axis.text = element_text(colour = "lightgrey"),
    axis.title = element_text(colour = "lightgrey"),
    plot.title = element_text(colour = "white", hjust=.5, face="bold", size = 11),
    plot.subtitle = element_text(colour = "white", hjust=.5, face="bold", size = 8)) +
  labs(title = "Offensive vs Defensive Ratings of Best Players on Championship Teams (2008-2022)",
       subtitle = "") +
  xlab("Offensive Rating") +
  ylab("Defensive Rating") +
  scale_y_reverse()
 
nba
```

```{r}
player_shooting_1 = read_csv("PPP.csv")
player_shooting_1
player_shooting_2 = read_csv("PPP_2.csv")
player_shooting_2
```

#Bar Plot
```{r}
bar_chart <- ggplot() +
  # bar chart function from ggplot
  geom_bar(player_shooting_2, mapping = aes(x = season, y = value, group = season, fill = season), 
           stat = "identity", position = position_dodge(), color = "white", width = 3) +
  geom_line(data = player_shooting_2, 
            aes(x = season, y = value, group = name), 
            color = "gray") +

 scale_y_continuous(limits=c(0, 1), expand = c(0,0), labels = scales::percent_format()) +
  
  scale_fill_manual(values = c("#1D428A","#FFC72C","#552583","#00471B","#CE1141")) +
  scale_x_discrete(limits=player_shooting_2$season) +
 
  facet_wrap(~name) +
 
  labs(title = "NBA Finals Teams Shooting Percentage Trends (2018-2022) ",
       x = "Championship Team (2018-2022)",
       y = "Shooting Allocation Percentage\n") +
 
  geom_text(player_shooting_2, mapping = aes(x = season, y = value,label = paste0(value*100, "%")), 
            position = position_dodge(width = .9), size = 4, family = "Comic Sans MS", color = "white", vjust = 2) +
 
  theme(
    
        plot.title = element_text(hjust = .5, size = 13, family = "Comic Sans MS", color = "white"),
        plot.subtitle = element_text(hjust = .5, size = 8, family = "Comic Sans MS", color = "gray50"),
        text = element_text(family = "Comic Sans MS"),
        legend.position = "none",
  
        plot.background = element_rect(fill="gray15", color = "gray15"),
        panel.background = element_rect(fill="gray15", color = "gray15"),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.y = element_line(colour = "gray20"),
        panel.grid.major.x = element_blank(),
        axis.line = element_line(colour = "white"),
        # axis
        axis.title.x = element_text(colour = "white", size = 20),
        axis.title.y = element_text(colour = "white", size = 18),
        axis.text.x = element_text(colour = "white", size = 12),
        axis.text.y = element_text(colour = "white", size = 8),
        plot.margin = margin(.5, .5, .5, .5, "cm"),
        # facet 
        strip.background = element_rect(fill="gray20"),
        strip.text = element_text(hjust = .5, size = 8, family = "Comic Sans MS", face = "bold", color = "white"))

bar_chart

```


#Bar Plot 2
```{r}
bar_chart <- ggplot() +

  geom_bar(player_shooting_1, mapping = aes(x = season, y = value, group = name, fill = season), 
           stat = "identity", position = position_dodge(), color = "white", width = 2.5) +
 geom_line(data = player_shooting_1, 
            aes(x = season, y = value, group = name,fill=season), 
            color = "gray") +

 scale_y_continuous(limits=c(0, 1), expand = c(0,0), labels = scales::percent_format()) +
  
  scale_fill_manual(values = c("#1D428A","#CE1141","black"))+
  scale_x_discrete(limits=player_shooting_1$season) +
  facet_wrap(~name) +
   labs(title = "NBA Finals Teams Average Shooting Percentage Trends (2008-2012 vs 2013-2017 vs 2018-2022) ",
       x = "5 Year Segments",
       y = "Shooting Allocation Percentage\n") +
  geom_text(player_shooting_1, mapping = aes(x = season, y = value,label = paste0(value*100, "%")), 
            position = position_dodge(width = .9), size = 4, family = "Comic Sans MS", color = "white", vjust = 2) +
  theme(
        plot.title = element_text(hjust = .5, size = 10, family = "Comic Sans MS", color = "white"),
        plot.subtitle = element_text(hjust = .5, size = 8, family = "Comic Sans MS", color = "gray50"),
        text = element_text(family = "Comic Sans MS"),
        legend.position = "none",
        plot.background = element_rect(fill="gray15", color = "gray15"),
        panel.background = element_rect(fill="gray15", color = "gray15"),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.y = element_line(colour = "gray20"),
        panel.grid.major.x = element_blank(),
        axis.line = element_line(colour = "white"),
        axis.title.x = element_text(colour = "white", size = 20),
        axis.title.y = element_text(colour = "white", size = 18),
        axis.text.x = element_text(colour = "white", size = 12),
        axis.text.y = element_text(colour = "white", size = 8),
        plot.margin = margin(.5, .5, .5, .5, "cm"),
        # facet 
        strip.background = element_rect(fill="gray20"),
        strip.text = element_text(hjust = .5, size = 8, family = "Comic Sans MS", face = "bold", color = "white"))

bar_chart
```


# Basketball Pie Charts
```{r}
index <- 1:12
stat <- c("Transition", "P&R Ball Handler", "Isolation", "Spot-Up", "Post-Up", "Cut",
          "P&R Ball Handler D", "Isolation D", "Post-Up D", "Handoffs", "Off Screen D","Spot-Up D")
value <- c("97", "91", "91", "96", "69", "90", "86", "51", "97", "61", "58","54")
data <- as.data.frame(cbind(index, stat, value))
data <- data %>% 
  mutate(type = case_when(
    index %in% 1:6 ~ "Scoring",
    index %in% 7:12 ~ "Defending"
  ))
data$index <- as.numeric(data$index)
data$value <- as.numeric(data$value)
data$type <- factor(data$type, levels = c("Scoring","Defending"))
```

```{r}
color1 <- "#98002E"
color2 <- "#F9A01B"
color3 <- "#FDB927"
ggplot(data = data, aes(x = reorder(stat, index), y = value, label= value, fill = type)) +
  geom_bar(data = data, width = 1,
           color = "oldlace",
           stat = "identity") +
  coord_curvedpolar() +  
  geom_bar(aes(y=100, fill=type), stat="identity", width=1, alpha=0.5) +
  geom_hline(yintercept = seq(0, 100, by = 100),
             color = "oldlace",
             size = 1) +
  geom_vline(xintercept = seq(.5, 12, by = 1),
             color = "oldlace",
             size = .5) +
  geom_label(color = "gray20", fill = "oldlace", size=2.5, fontface="bold", family = "Comic Sans MS", show.legend = FALSE) +
  scale_fill_manual(values=c(color1, color2, color3)) +
  theme(legend.position = "top",
        legend.direction = "horizontal",
        legend.background = element_rect(fill = "gray15", color="gray15"),
        legend.title = element_blank(),
        legend.text = element_text(colour = "white", family = "Comic Sans MS", face = "bold"),
        legend.key.size = unit(.5, "cm"),
        legend.box.spacing = unit(0, "mm"),
        plot.title = element_text(hjust = .5, colour = "white", face = "bold", size = 11, family = "Comic Sans MS"),
        plot.subtitle = element_text(hjust = .5, colour = "white", size = 8, family = "Comic Sans MS"),
        plot.background = element_rect(fill = "gray15", color="gray15"),
        panel.background = element_rect(fill = "gray15", color="gray15"),
        panel.grid = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_text(face = "bold", size = 6.8, colour = "white"),
        axis.title = element_blank(),
        axis.text.x = element_text(face = "bold", size = 7, family = "Comic Sans MS")) +
  labs(title = "Lebron James 2012-2013 Percentile Rankings",
       subtitle = "via: Synergy", x = NULL, y = NULL)

```


